### ISSUE TITLE
Filters out messages with items that contain keyword

### ISSUE THREAD

**Issue by Blazeflack** [funkydude/BadBoy_CCleaner#1]
By default the CCleaner blocks the keywords "anal" and "rape". The following message was blocked from trade due to the "rape" keyword:

> WTS [Drape of the Forgotton Souls]

**Comment by funkydude** [comment]
Technically, working as intended.

**Comment by Blazeflack** [comment]
Blocking legitimate messages can't really be the "intended" way for it to work. Any chance it can somehow detect if keyword is part of an item string and ignore it in that case?

**Comment by funkydude** [comment]
That would create problems with people purposely wanting to filter out items, such as thunderfury :/

**Comment by Blazeflack** [comment]
Hmm fair point. I guess there is no solution that will satisfy all criterias. I'll just remove the rape keyword.

**Comment by funkydude** [comment]
Eventually I want to have keywords set on a per channel basis, maybe that will satisfy.
