### ISSUE TITLE
Any version for Classic?

### ISSUE THREAD

**Issue by nezorflame** [funkydude/BadBoy_CCleaner#11]
Hi. This is not an issue, more like a question. Is there any version for Classic? I haven't seen anything on CurseForge except for the base addon. But the addon itself is kinda irrelevant without the plugins, which are missing for the Classic version, hence the question.

**Comment by allieIsOkay** [comment]
@nezorflame While it's maybe not helpful in terms of ability to manage the plugin using an addon manager, I had the same question and figured I'd try the retail plugin on the classic client. I've yet to encounter any issues with doing this and the plugin appears to be fully functional.

![image](https://user-images.githubusercontent.com/41562392/116248172-75ad0f00-a720-11eb-819e-b3f80ead195f.png)

I'm admittedly not familiar with the requirements to host a classic version on wowinterface or curseforge so I can't say with any confidence that the process wouldn't be involved to host a classic version. However, looking at the main addon's repo it certainly seems like something that _could_ be a fairly small effort. 

In either case, using the retail plugin isn't too troublesome and works for you as well.

**Comment by nezorflame** [comment]
@plapicola AFAIK it's just a matter of uploading the same plugin(s) while marking it compatible with the Classic version of WoW.
You're right, it's not hard to do it myself, but since the addon itself is uploaded to CurseForge in two versions, I'd like to see its plugins having the same treatment.

**Comment by Mixuspidelix** [comment]
![WoWScrnShot_050621_131235](https://user-images.githubusercontent.com/18029891/117289945-828ed880-ae6d-11eb-868b-25b9e35916eb.jpg)
I use the BadBoy Classic variant for Wow Classic with the CCleaner v9.0.2 and get this Lua_Error with only activated Badboy + CCleaner :(

**Comment by funkydude** [comment]
Eventually
