### ISSUE TITLE
(Feature Request) Would you add an option to also auto-report?

### ISSUE THREAD

**Issue by ars4l4n** [funkydude/BadBoy_CCleaner#13]
I mean if I use this addon to auto-ignore all the spammers in trade chat then I won't see them but my fellow players will, therefore most players still won't use trade chat.
But an auto-reporter would change the situation. as soon as even a few users started using it.
I've tried manually reporting gold-sellers but the ones on my server just create one account after another, presumably with bots, and flood the chat so heavily that it's impossible to keep up with manual reports.

**Comment by funkydude** [comment]
There's no such thing as "auto reporting" in the game anymore, but regardless, no. This addon is purely for filtering.
