### ISSUE TITLE
Not working in guild chat ? (TLK Classic)

### ISSUE THREAD

**Issue by Kinchipwet** [funkydude/BadBoy_CCleaner#14]
## Describe the problem
People are starting to spam achievement with Attune + Weakauras that congratulate people on achievements sharing. Kinda annoying. I tried to use Badboy + Badboy_CCleaner

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
1st screenshot : On my main account, trying to avoid spam. This is my config.
![image](https://user-images.githubusercontent.com/112708621/188159903-40bc2eb5-0c04-4abd-b42b-6d9483726adf.png)
2nd screenshot : Same account : trying to see if it works, but it doesn't.
![image](https://user-images.githubusercontent.com/112708621/188159975-90076c43-cacc-4667-9c55-94dfbee0e5f8.png)

### What version of the addon are you using? (Stating 'latest' is not useful)
v9.2.4

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English)
Using english client with english language.

Also, using ElvUI.

**Comment by Kinchipwet** [comment]
"The following are not scanned and cannot be reported/blocked by this addon: Friends, Real ID friends, Guild, Party, Raid, GM's. The following channels are monitored: Trade, General, Yell, Whispers."

Sorry for the disturbance.

**Comment by funkydude** [comment]
@realrobd acting like a moron is a good way to get yourself banned across all my addons 👋
