### ISSUE TITLE
the word "string"

### ISSUE THREAD

**Issue by Striding** [funkydude/BadBoy_CCleaner#2]
Apparently the word "string" can't be blocked. Something with the code of the addon?

(if you're guessing why I want to block it, it's because people on my country/server can't say my character name right - Striding - without mispelling or shortening it wrong) and that's the only that can't be blocked.

**Comment by funkydude** [comment]
There's nothing in the code blocking specific words, only specific symbols.
Is the problem that you can't add it, or that it's added but not working?

**Comment by Striding** [comment]
it's added, with a bunch of variations, and it doesn't block on chat
![badboy](https://user-images.githubusercontent.com/8939367/34957227-db90c194-fa13-11e7-91f6-476bbbd2c4b2.png)


The "string" is cut at the top.

**Comment by funkydude** [comment]
Can you elaborate on "people"? This addon only filters public chat and yells, and only if they aren't your friend, guild member, etc.

**Comment by Striding** [comment]
So that's why it's not blocking: "friend, guild member, etc.", that must be it.
By people I mean players on my region/country that doesn't know english that well.

**Comment by funkydude** [comment]
Yes anyone that's potentially friendly (guild member, friends list, in your group) will not be filtered. This addon is mostly designed to clear up random public chat.
