### ISSUE TITLE
Uppercase letters will be automatically converted to lowercase

### ISSUE THREAD

**Issue by cikichen** [funkydude/BadBoy_CCleaner#4]
Uppercase letters will be automatically converted to lowercase

**Comment by funkydude** [comment]
You haven't described what the issue is.

It sounds like you're describing the text input.
This is done on purpose to help you block people that "miX UppEr caSe" with lowercase.

**Comment by cikichen** [comment]
> You haven't described what the issue is.
> 
> It sounds like you're describing the text input.
> This is done on purpose to help you block people that "miX UppEr caSe" with lowercase.

Yes, if the keyword is entered in uppercase letters, it will be automatically converted to lowercase, which will prevent the uppercase text from being masked.

**Comment by funkydude** [comment]
But I'm still not sure what the issue here is. All text is changed to lowercase before it is scanned for keywords.
