### ISSUE TITLE
Drape of Valiant Defense

### ISSUE THREAD

**Issue by kevinhyatt** [funkydude/BadBoy_CCleaner#5]
Hello, I noticed there is an issue where any chat message containing a trigger word gets filtered.

I'd like to suggest that you make it so we can specify weather the word has to be by itself, or included in other words... IE

adding
*rape*
to the filter list, will filter anything containing those 4 letters in that order, regardless of what comes before or after it.
while adding..
 rape 
with a space at the start and end, will filter out messages containing only that word specifically, so things like
Drape, Scrape, Grape, Cameraperson etc.. don't get filtered.

**Comment by funkydude** [comment]
Perhaps it can be made more advanced in the future, but for now, the default database will be empty.
